name: Train and Push Model

on:
  workflow_dispatch:  # déclenchement manuel

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Run training
        run: |
          python train.py \
            --xml_dir plagiarism-annotations \
            --susp_dir suspicious-documents \
            --src_dir source-documents \
            --out_dir data \
            --model_out best_model.pth \
            --batch_size 8 \
            --epochs 5 \
            --max_len 128 \
            --augment

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_file(
            path_or_fileobj='best_model.pth',
            path_in_repo='best_model.pth',
            repo_id='TON_UTILISATEUR/arabic-plag-detector-model',
            token='${{ secrets.HF_TOKEN }}'
          )
          "
